export const USER_INIT = 'USER_INIT'
export const USER_LOGOUT = 'USER_LOGOUT'

export const CATEGORIES_FETCH = 'CATEGORIES_FETCH'
export const CATEGORIES_FETCH_SUCCESS = 'CATEGORIES_FETCH_SUCCESS'

export const EXERCISES_FETCH = 'EXERCISES_FETCH'
export const EXERCISES_FETCH_SUCCESS = 'EXERCISES_FETCH_SUCCESS'

export const NOTIFICATIONS_FETCH_SUCCESS = 'NOTIFICATIONS_FETCH_SUCCESS'
export const NOTIFICATIONS_UPDATE = 'NOTIFICATIONS_UPDATE'
